# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               David Pottinger Design
tagline:             'an electronics blog'
description:         'These are the brief moments I can scribble about what I am trying to make.'
url:                 http://davidpottingerdesign.github.io
baseurl:             'http://davidpottingerdesign.github.io'
paginate:            5

# About/contact
author:
  name:              David Pottinger
  email:             davidpottingerdesign@gmail.com
  
  timezone:         America/Los_Angeles
