# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               David Pottinger Design
tagline:             'a journal blog'
description:         'An attempt to scribble about my life regularly.'
url:                 http://davidpottingerdesign.github.io
baseurl:             'http://davidpottingerdesign.github.io'
paginate:            5

# About/contact
author:
  name:              David Pottinger
  email:             davidpottingerdesign@gmail.com
  
  timezone:         America/Los_Angeles
